# Generated by Django 4.2.2 on 2023-06-21 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('DateAdd', models.DateTimeField(default=datetime.datetime(2023, 6, 21, 16, 13, 35, 393360))),
                ('DateDel', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('DateOfBirth', models.DateTimeField()),
                ('DateAdd', models.DateTimeField(default=datetime.datetime(2023, 6, 21, 16, 13, 35, 393360))),
                ('DateDel', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicensePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='PassportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssuedByWhom', models.CharField(max_length=500)),
                ('DateOfIssue', models.DateTimeField()),
                ('DivisionCode', models.CharField(max_length=255)),
                ('Series', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=255)),
                ('FIO', models.CharField(max_length=255)),
                ('IsMale', models.BooleanField(default=True)),
                ('DateOfBirth', models.DateTimeField(default=datetime.date(2023, 6, 21))),
                ('PlaceOfBirth', models.CharField(max_length=500)),
                ('ResidenceAddress', models.CharField(max_length=500)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_insurance.client')),
                ('Photos', models.ManyToManyField(blank=True, null=True, to='car_insurance.passportphoto')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfIssue', models.DateTimeField()),
                ('ExpirationDate', models.DateTimeField()),
                ('CodeGIBDD', models.CharField(max_length=255)),
                ('Series', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=255)),
                ('TransmissionType', models.CharField(max_length=255)),
                ('VehicleCategories', models.CharField(max_length=255)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_insurance.client')),
                ('Photos', models.ManyToManyField(blank=True, null=True, to='car_insurance.licensephoto')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='car_insurance.employee'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationNumber', models.CharField(max_length=255)),
                ('IdNumber', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('TCType', models.CharField(max_length=255)),
                ('TCCategory', models.CharField(max_length=255)),
                ('YearOfIssue', models.IntegerField()),
                ('EngineModel', models.CharField(max_length=255)),
                ('EngineNumber', models.CharField(max_length=255)),
                ('ChassisNumber', models.CharField(max_length=255)),
                ('CarBodyNumber', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('EnginePower', models.CharField(max_length=255)),
                ('EngineDisplacement', models.IntegerField()),
                ('Series', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=255)),
                ('MaxWeightPermitted', models.IntegerField()),
                ('WeightWithoutCapacity', models.IntegerField()),
                ('NameOwner', models.CharField(max_length=255)),
                ('PlaceRegistration', models.CharField(max_length=255)),
                ('PlaceOfIssue', models.CharField(max_length=255)),
                ('DateOfIssue', models.DateTimeField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_insurance.client')),
                ('Photos', models.ManyToManyField(blank=True, null=True, to='car_insurance.carphoto')),
            ],
        ),
    ]
