# Generated by Django 4.2.2 on 2023-07-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carphoto',
            old_name='date_delete',
            new_name='DateDel',
        ),
        migrations.RenameField(
            model_name='carphoto',
            old_name='photo_path',
            new_name='Path',
        ),
        migrations.RenameField(
            model_name='licensephoto',
            old_name='date_delete',
            new_name='DateDel',
        ),
        migrations.RenameField(
            model_name='licensephoto',
            old_name='photo_path',
            new_name='Path',
        ),
        migrations.RenameField(
            model_name='passportphoto',
            old_name='date_delete',
            new_name='DateDel',
        ),
        migrations.RenameField(
            model_name='passportphoto',
            old_name='photo_path',
            new_name='Path',
        ),
        migrations.AddField(
            model_name='car',
            name='DateDel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='DateDel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='DateDel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='DateAdd',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 2, 55, 31, 677357)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DateAdd',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 2, 55, 31, 677936)),
        ),
        migrations.AlterField(
            model_name='passport',
            name='DateOfBirth',
            field=models.DateTimeField(default=datetime.date(2023, 7, 18)),
        ),
    ]
