# Generated by Django 4.2.2 on 2023-07-26 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_insurance', '0002_rename_date_delete_carphoto_datedel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='IsAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='DateAdd',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 9, 9, 46, 662444)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DateAdd',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 9, 9, 46, 663044)),
        ),
        migrations.AlterField(
            model_name='passport',
            name='DateOfBirth',
            field=models.DateTimeField(default=datetime.date(2023, 7, 26)),
        ),
    ]
